# -----------------------------------------------------------------------------------------------------------------
#  TODO: set sudo: false and remove before_script when https://github.com/travis-ci/travis-ci/issues/7703 is fixed
# -----------------------------------------------------------------------------------------------------------------
sudo:
  - required
before_script:
  - sudo chmod +x /usr/local/bin/sbt
language:
  - scala
scala:
  - 2.11.11
  - 2.12.2
jdk:
  - oraclejdk8
